### ISSUE TITLE
Secondary rate limit while fetching and deleting packages

### ISSUE THREAD

**Issue by JulesClaussen** [snok/container-retention-policy#93]
Hey,

First of all, thanks for the plugin, it works quite well!
However, we have some troubles with the secondary rate limit (using snok/container-retention-policy@v3.0.0). Both when searching, and deleting. See logs below.

When searching:
```
2024-07-15T15:12:26.383694Z ERROR container_retention_policy: Failed to fetch package versions: Failed to deserialize paginated response: {
  "documentation_url": "https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits",
  "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID <some-request-id>"
}. The error was invalid type: map, expected a sequence at line 1 column 0.
```

When deleting:
```
2024-07-15T15:14:38.939471Z ERROR container_retention_policy::client::client: Failed to delete package version <my-package-version> with status 403 Forbidden: {
  "documentation_url": "https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits",
  "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID <some-request-id>."
}
```

To workaround this we increase the cut-off, but it's hard to find a soft spot (especially when we haven't deleted images in some repos for a couple of years). 

Note that the searching rate limit does stop the job. While the deleting one keeps going (and deletes some more after a couple of fails, which is quite handy).

Let me know if you need more details for that.
Cheers,
Jules

**Comment by sondrelg** [comment]
Some quick first thoughts:

I could be wrong about this, but I think we adequately handle secondary rate-limits in the action currently, *assuming that nothing else is consuming the same rate-limit budget*. The rate-limit is account or org-wide, so other actions running at the same time, might cause things to fail. Here are the docs on secondary rate-limits: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits

We don't currently handle the `No more than 90 seconds of CPU time per 60 seconds of real time is allowed` limit, so if that's the problem here we may want to add handling for that specifically. Perhaps you'd be willing to ask support which limit is broken in this case?

Assuming it's not the CPU-minutes one, and that it's the combination of this action running while other actions are running elsewhere in your org: I suppose we could add an input that would allow you to specify which % of the rate limit to consume, or something like that, to not consume 100% of it and break the limits when other actions are running.

Do you have other suggestions?

**Comment by JulesClaussen** [comment]
Hi @sondrelg thanks for quick feedback.

I'll raise a ticket to the support to have more details about the rate limit.
However, some of the rate limits (the searching ones) were occurring event at night time when I'm sure there were no pipelines running org-wide. So this one specifically is likely to happen due to the 90s of CPU time per 60s of real time. 
For the delete event, it's quite likely that we had concurrent workflows running at the same time as you mentioned.

Having a % of rate limit would indeed help. 
However, maybe there could be a way to get the current rate account/org-wide and if we're close to it (95% for example), the action pauses any more search for 30 seconds then retry. After 3 failed retry, the action would overall fail with an error message stating that rate limit would hit, so not pursuing. In my opinion that sounds like a more reliable options as we would stop before the rate limit, and not block the other workflows.
What do you think?

**Comment by sondrelg** [comment]
I haven't seen any docs mention a way to get estimates for the % use of secondary rate limits, but I'd definitely be willing to add some handling for it if there was one!

If there's no way to get this reported to us directly, then for the 90s of CPU time per 60s of real time, I guess we could time each response's response time and aggregate it, to be able to make an estimate of what we've roughly spent. That doesn't sound very precise, but if that's the only rate-limit we're not handling appropriately, then perhaps it's worth investigating.

**Comment by sondrelg** [comment]
Perhaps it would be just as effective to set a hard-limit of total requests to make, across endpoints, before exiting? 

Just exploring the idea here: since the rate-limit resets every minute, would the simplest solution be to just schedule the action to run every `n` minutes, and exit as soon as it gets to some user-specified limit? The action can exhaust the minute rate-limit in a few seconds, so if we opt for sleeping until the next rate-limit reset, we have pretty high % of downtime 

We could maybe allow a max-limit for total requests, but we could also try to estimate CPU time and allow setting a limit for that. 

What do you think of a fast exit, vs. sleeping, for your use-case?

**Comment by JulesClaussen** [comment]
On one hand the sleeping is good because this action is basically a cleanup that happens in background, is not supposed to blocked anyone and is scheduled frequently. On the other hand sleeping may cause pipeline to run for hours, so exhaust / block runners. What if we use the sleep, with a parameter to set a timeout for the job? Then we're sure it doesn't run for hours.

Or even a "strategy" where users could pick between a max-limit total request and sleeping.

In my case the max-limit is not the solution, because I have thousands of images to delete. So I don't mind if this runs for 1 hour, as long as it deletes all the images older than a couple. This would run at night time where no one uses the CI, and the runners are not autoscaling (so no pricing change between one job for 10 hours or 0 jobs).
But I definitely think people using Github actions cloud (not self hosted runners) won't want a 10 hour job to run. That would kill their github minutes available.

**Comment by JulesClaussen** [comment]
Hey @sondrelg, do you think a workaround could be implemented? If so, do you maybe have an ETA on that one?

Thanks a lot!

**Comment by sondrelg** [comment]
Looking at this again, wouldn't it be better for you to just run the action for a subset of images, on a schedule that accommodates rate limit resets? If you do run into the secondary rate limit for old repos, perhaps just schedule these at night? 

Not sure how to build this into the action, and don't have a lot of spare time on my hands these days, so don't think I'll be able to do this any time soon.

**Comment by JulesClaussen** [comment]
Yes makes sense, thanks for quick feedback!
It's taking quite a while to run the action on subset of images, because I need to find the soft spot where I delete some, and where it rates limit. So I need to iterate quite a lot (we have thousands of images over a dozen of repos). I'll try to think about a smart way to approach this. Thanks!

**Comment by sondrelg** [comment]
I understand! Any reason why you can't just schedule it to run every few minutes at night time, and just let it hit the rate limit? It should delete 1000+ images every run. I suppose you might have other workflows you need to run at this time?
